# Actionlint configuration
# Docs: https://rhysd.github.io/actionlint/
# GitHub: https://github.com/rhysd/actionlint
# Configuration file: https://github.com/rhysd/actionlint/blob/main/docs/config.md
