# Gitleaks configuration
# Docs: https://github.com/gitleaks/gitleaks
# GitHub: https://github.com/gitleaks/gitleaks
# Configuration file: https://github.com/gitleaks/gitleaks/blob/master/README.md#configuration
