# TruffleHog configuration
# Docs: https://docs.trufflesecurity.com/
# GitHub: https://github.com/trufflesecurity/trufflehog
# Configuration file: https://docs.trufflesecurity.com/configuration-file-reference
